language: node_js
sudo: false
node_js:
  - "0.12"
  - "0.11"
services:
  - mongodb
notifications:
  irc:
    channels:
      - "irc.esper.net#bukget"
    skip_join: true
    on_success: change
    on_failure: always
  email:
    recipients:
      - david@dmarby.se
    on_success: change
    on_failure: always
